version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r app/requirements.txt
      - pip install pytest

  pre_build:
    commands:
      - echo "Verificando versiones..."
      - python --version
      - docker --version

  build:
    commands:
      - echo "Ejecutando pruebas..."
      - pytest tests/ || echo "No hay tests aún, continuando..."
      - echo "Construyendo imagen Docker..."
      - docker build -t mi-flask-app ./app

  post_build:
    commands:
      - echo "Construcción finalizada con éxito"
      - docker tag mi-flask-app:latest mi-flask-app:$CODEBUILD_BUILD_NUMBER

artifacts:
  files:
    - appspec.yml
    - docker-compose.yml
    - app/**/*
    - scripts/**/*
